int_libs = # Interface dependencies.
imp_libs = # Implementation dependencies.

lib{pest}: {hxx ixx txx}{**} $imp_libs $int_libs

cxx.poptions =+ "-I$out_root" "-I$src_root"

export_poptions =

switch $cxx.class
{
  case 'gcc'
  {
    # disable warnings that pop up with -Wall -Wextra ( and -Weverything in case of clang ).
    #
    #cc.coptions += -Wno-all -Wno-extra -Wno-pedantic -Wno-error
    if ( $cxx.id == 'clang' )
      export_poptions += -Wno-c++98-compat -Wno-padded -Wno-c++98-compat-pedantic \
        -Wno-weak-vtables -Wno-exit-time-destructors -Wno-global-constructors -Wno-unused-template
  }
}

lib{pest}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root" $export_poptions
  cxx.export.libs = $int_libs
}

# Install into the pest/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/pest/
  install.subdirs = true
}
