int_libs = # Interface dependencies.
imp_libs = # Implementation dependencies.

lib{pest}: {hxx ixx txx}{**} $imp_libs $int_libs

cxx.poptions =+ "-I$out_root" "-I$src_root"

lib{pest}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $int_libs
}

# Install into the pest/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/pest/
  install.subdirs = true
}
